ams-personal

diff --git a/share/scripts/ams-sync b/share/scripts/ams-sync
--- a/share/scripts/ams-sync
+++ b/share/scripts/ams-sync
@@ -55,6 +55,9 @@ function read_profile()
         exit 1
     fi
 
+    export AMS_DST_PKGROOT="`grep DST_PKGROOT "$PROFILE" | awk '{print $2;}'`"
+    echo "  Destination package :   $AMS_DST_PKGROOT"
+
     export AMS_DST_SOFTMODS="`grep DST_SOFTMODS "$PROFILE" | awk '{print $2;}'`"
     echo "  Destination softmods:   $AMS_DST_SOFTMODS"
     if [ -z "$AMS_DST_SOFTMODS" ]; then
@@ -147,13 +150,6 @@ done
 if [ $# -ne 1 ] && [ $# -ne 2 ] && [ $# -ne 3 ]; then
     echo "" 1>&2
     echo ">>> ERROR: Incorrect number of parameters!" 1>&2
-    print_usage
-    exit 1
-fi
-
-if [ -n "$AMS_SYNC_ACTION" ] && [ $# -ge 2 ]; then
-    echo "" 1>&2
-    echo ">>> ERROR: ACTION can be provided via the profile or command argument but not both!" 1>&2
     print_usage
     exit 1
 fi
@@ -287,6 +283,13 @@ function sync_profile() {
                 echo "" 1>&2
                 exit 1
             fi
+            if [ -n "AMS_SYNC_ACTION" ] && [ -n "$2" ]; then
+                echo "" 1>&2
+                echo ">>> ERROR: ACTION is specified both via the profile and command argument!" 1>&2
+                echo "" 1>&2
+                exit 1
+            fi
+
             if [ -n "$AMS_SYNC_ACTION" ]; then
                 $AMS_ROOT/share/sync/rsync/ams-rsync-push "$AMS_SYNC_ACTION"
             else
@@ -298,14 +301,14 @@ function sync_profile() {
             AMS_DST_HOSTNAME="`echo $AMS_DST_HOST | cut -f 2 -d @`"
             if [ $AMS_DST_HOSTNAME != "$HOSTNAME" ]; then
                 echo "" 1>&2
-                echo ">>> ERROR: Sync can be commence only from destination machine $AMS_DST_HOSTNAME!" 1>&2
+                echo ">>> ERROR: Sync can be initialized only from destination machine $AMS_DST_HOSTNAME!" 1>&2
                 echo "" 1>&2
                 exit 1
             fi
             AMS_DST_USER="`echo $AMS_DST_HOST | cut -f 1 -d @`"
             if [ $AMS_SRC_USER != "$USER" ]; then
                 echo "" 1>&2
-                echo ">>> ERROR: Sync can be commence only by $AMS_DST_USER user!" 1>&2
+                echo ">>> ERROR: Sync can be initialized only by $AMS_DST_USER user!" 1>&2
                 echo "" 1>&2
                 exit 1
             fi
diff --git a/share/sync/rsync/ams-rsync-push b/share/sync/rsync/ams-rsync-push
--- a/share/sync/rsync/ams-rsync-push
+++ b/share/sync/rsync/ams-rsync-push
@@ -140,6 +140,13 @@ rsync_amscore()
 
 rsync_dpkg()
 {
+    if [ -z "$AMS_DST_PKGROOT" ];then
+        echo "" 1>&2
+        echo ">>> ERROR: DST_PKGROOT key is not defined!" 1>&2
+        echo "" 1>&2
+        exit 1
+    fi
+
     echo "" | tee -a $LOG_FILE
     echo "# AMS dpkg - sync data" | tee -a $LOG_FILE
     echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE
