ams-personal

diff --git a/share/sync/rsync/ams-rsync-pull b/share/sync/rsync/ams-rsync-pull
--- a/share/sync/rsync/ams-rsync-pull
+++ b/share/sync/rsync/ams-rsync-pull
@@ -87,7 +87,7 @@ show_log_error()
 test_password_less_ssh()
 {
     echo -n ">>> Testing connection to: $AMS_SRC_HOST ... " | tee -a $LOG_FILE
-    ssh -x -o "BatchMode=yes" "$AMS_SRC_HOST" "/bin/echo" >> $LOG_FILE 2>&1
+    ssh -x -o "BatchMode=yes" -o "StrictHostKeyChecking=no" "$AMS_SRC_HOST" "/bin/echo" >> $LOG_FILE 2>&1
     if [ $? -ne 0 ]; then
         echo "failure" | tee -a $LOG_FILE
         echo "" 1>&2
@@ -125,7 +125,7 @@ rsync_amscore_cache()
 rsync_amsbuilds()
 {
     echo "" | tee -a $LOG_FILE
-    echo "# AMS builds and master index - sync data" | tee -a $LOG_FILE
+    echo "# AMS builds - sync data" | tee -a $LOG_FILE
     echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE
 
     umask 022
@@ -134,29 +134,45 @@ rsync_amsbuilds()
         if [ $? -ne 0 ]; then exit 1; fi;
     fi
 
+    echo -n "AMS builds synchronization           ... "
+
     rsync -e "ssh -x" -av --delete $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w --exclude-from=$AMS_ROOT/share/sync/rsync/ams-exclude-rules-blds \
          "$AMS_SRC_HOST:$AMS_SRC_SOFTMODS/etc/map/" "$AMS_DST_SOFTMODS/etc/map/" >> $LOG_FILE 2>&1
 
     if [ $? -eq 0 ]; then
-        echo "AMS builds synchronization           ... [OK]"
+        echo "[OK]"
     else
-        echo "AMS builds synchronization           ... [FAILED]"
+        echo "[FAILED]"
         show_log_error
         exit 1
     fi
+}
+
+# -------------------------------------------------------------------------------------
+
+rsync_amsindex()
+{
+    echo "" | tee -a $LOG_FILE
+    echo "# AMS master index - sync data" | tee -a $LOG_FILE
+    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE
+
+    umask 022
+
+    echo -n "AMS master index synchronization ... "
 
     if [ -n "$AMS_MASTER_INDEX" ]; then
         scp "$AMS_SRC_HOST:$AMS_SRC_SOFTMODS/var/sync/$AMS_MASTER_INDEX/index.old" "$MST_INDEX" >> $LOG_FILE 2>&1
 
         if [ $? -eq 0 ]; then
-            echo "AMS master index synchronization ... [OK]"
+            echo "[OK]"
         else
-            echo "AMS master index synchronization ... [FAILED]"
+            echo "[FAILED]"
             show_log_error
             exit 1
         fi
     fi
 }
+
 
 # -------------------------------------------------------------------------------------
 
@@ -238,6 +254,8 @@ case "$ACTION" in
         ;;
     "softrepo")
         rsync_amscore_cache
+        if [ $? -ne 0 ]; then exit 1; fi;
+        rsync_amsindex
         if [ $? -ne 0 ]; then exit 1; fi;
         rsync_softrepo
         if [ $? -ne 0 ]; then exit 1; fi;
diff --git a/share/sync/rsync/ams-rsync-push b/share/sync/rsync/ams-rsync-push
--- a/share/sync/rsync/ams-rsync-push
+++ b/share/sync/rsync/ams-rsync-push
@@ -89,7 +89,7 @@ show_log_error()
 test_password_less_ssh()
 {
     echo -n ">>> Testing connection to: $AMS_SRC_HOST ... " | tee -a $LOG_FILE
-    ssh -x -o "BatchMode=yes" "$AMS_SRC_HOST" "/bin/echo" >> $LOG_FILE 2>&1
+    ssh -x -o "BatchMode=yes" -o "StrictHostKeyChecking=no" "$AMS_SRC_HOST" "/bin/echo" >> $LOG_FILE 2>&1
     if [ $? -ne 0 ]; then
         echo "failure" | tee -a $LOG_FILE
         echo "" 1>&2
@@ -266,7 +266,7 @@ rsync_softrepo()
         BACKUP_PWD=$PWD
         cd $AMS_SRC_SOFTREPO
         echo $AMS_PACKAGE_DIR | tr '/' '\n' | while read A; do
-            stat --format="%n %G %a" $A
+            stat --format="%n %G %a" "$A"
             cd $A
         done > /tmp/perms.$$ 2>> $LOG_FILE
         cd $BACKUP_PWD
@@ -304,7 +304,7 @@ rsync_build()
     BUILD="`basename "$1"`"
     if [ "$PREFIX" == "." ]; then PREFIX=""; fi
 
-    BUILDS=`ams-map-manip --prefix "$PREFIX" getbuilds all "$BUILD" 2> /dev/null`
+    BUILDS=`ams-map-manip --prefix "$PREFIX" showautobuilds all "$BUILD" 2> /dev/null`
 
     for BUILD in $BUILDS; do
 
@@ -314,8 +314,13 @@ rsync_build()
 
         AMS_PACKAGE_DIR=`ams-map-manip --prefix "$PREFIX" getpkgdir all "$BUILD" 2> /dev/null`
 
+        if [ -z "$AMS_PACKAGE_DIR" ]; then
+            echo " - [ERROR] - package directory is not specified!"
+            exit 1
+        fi
+
         printf "%-60s " "$PREFIX/$BUILD"
-        echo "==== $PREFIX/$BUILD" >> $LOG_FILE
+        echo "==== $PREFIX/$BUILD ($AMS_PACKAGE_DIR)" >> $LOG_FILE
 
         if ! [ -d "$AMS_SRC_SOFTREPO/$AMS_PACKAGE_DIR/" ]; then
             echo " - [ERROR] - package directory does not exists: $AMS_SRC_SOFTREPO/$AMS_PACKAGE_DIR/"
@@ -326,7 +331,7 @@ rsync_build()
         BACKUP_PWD=$PWD
         cd $AMS_SRC_SOFTREPO
         echo $AMS_PACKAGE_DIR | tr '/' '\n' | while read A; do
-            stat --format="%n %G %a" $A
+            stat --format="%n %G %a" "$A"
             cd $A
         done > /tmp/perms.$$ 2>> $LOG_FILE
         cd $BACKUP_PWD
