ams-personal

diff --git a/share/sync/rsync/ams-rsync-push b/share/sync/rsync/ams-rsync-push
--- a/share/sync/rsync/ams-rsync-push
+++ b/share/sync/rsync/ams-rsync-push
@@ -138,6 +138,38 @@ rsync_amscore()
 
 # -------------------------------------------------------------------------------------
 
+rsync_dpkg()
+{
+    echo "" | tee -a $LOG_FILE
+    echo "# AMS dpkg - sync data" | tee -a $LOG_FILE
+    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE
+
+# AMS_DST_SOFTREPO - it is the root of the package
+
+    ssh -x $AMS_DST_HOST "if ! [ -d "$AMS_DST_SOFTREPO" ]; then mkdir -p "$AMS_DST_SOFTREPO" ; fi;" >> $LOG_FILE 2>&1
+    if [ $? -ne 0 ]; then exit 1; fi
+
+    ssh -x $AMS_DST_HOST "if ! [ -d "$AMS_DST_SOFTMODS" ]; then mkdir -p "$AMS_DST_SOFTMODS" ; fi;" >> $LOG_FILE 2>&1
+    if [ $? -ne 0 ]; then exit 1; fi
+
+    rsync -e "ssh -x" -av --delete $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w --exclude-from=$AMS_ROOT/share/sync/rsync/ams-dpkg-exclude-rules \
+         "$AMS_ROOT/" "$AMS_DST_HOST:$AMS_DST_SOFTMODS/" >> $LOG_FILE 2>&1
+
+    if [ $? -eq 0 ]; then
+        echo "AMS dpkg synchronization [OK]"
+        return 0
+    else
+        echo "AMS dpkg synchronization [FAILED]"
+        exit 1
+    fi
+
+    # copy DEBIAN package setup
+    rsync -e "ssh -x" -av --delete $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w  \
+         "$AMS_ROOT/share/dpkg/DEBIAN" "$AMS_DST_HOST:$AMS_DST_SOFTREPO/" >> $LOG_FILE 2>&1
+}
+
+# -------------------------------------------------------------------------------------
+
 rsync_softrepo()
 {
 # create new index file
@@ -224,6 +256,12 @@ case $ACTION in
         rsync_amscore_cache
         if [ $? -ne 0 ]; then exit 1; fi;
         rsync_amscore
+        if [ $? -ne 0 ]; then exit 1; fi;
+        ;;
+    "dpkg")
+        rsync_amscore_cache
+        if [ $? -ne 0 ]; then exit 1; fi;
+        rsync_dpkg
         if [ $? -ne 0 ]; then exit 1; fi;
         ;;
     "softrepo")
