ams-personal

diff --git a/share/personal/ams-personal b/share/personal/ams-personal
--- a/share/personal/ams-personal
+++ b/share/personal/ams-personal
@@ -4,6 +4,12 @@
 # (c) 2017 Petr Kulhanek
 # ------------------------------------------------------------------------------
 
+if [ -z "AMS_PERSONAL_ROOT" ]; then
+    echo "" 1>&2
+    echo ">>> ERROR: AMS_PERSONAL_ROOT is not set!" 1>&2
+    echo "" 1>&2
+fi
+
 # ------------------------------------------------------------------------------
 
 function print_usage()
@@ -47,83 +53,6 @@ function print_usage()
 }
 
 # ------------------------------------------------------------------------------
-
-function initenv_print_header()
-{
-    echo ""
-    echo "#------------------------------------------------------"
-    echo "#    *** Shell Environment Startup File Update ***     "
-    echo "#------------------------------------------------------"
-}
-
-# ------------------------------------------------------------------------------
-
-function initenv_backup_old_files()
-{
-    echo ""
-    echo "1) Backuping old user startup files ..."
-
-    SEQ=`date +"%s"`
-    if [ -f ~/.profile ]; then
-        mv ~/.profile ~/.profile.$SEQ
-        echo "   ~/.profile        -> ~/.profile.$SEQ"
-    fi
-    if [ -f ~/.bash_profile ]; then
-        mv ~/.bash_profile ~/.bash_profile.$SEQ
-        echo "   ~/.bash_profile   -> ~/.bash_profile.$SEQ"
-    fi
-    if [ -f ~/.bashrc ]; then
-        mv ~/.bashrc ~/.bashrc.$SEQ
-        echo "   ~/.bashrc         -> ~/.bashrc.$SEQ"
-    fi
-}
-
-# ------------------------------------------------------------------------------
-
-function initenv_create_new_files()
-{
-    echo ""
-    echo "2) Creating new user startup files ..."
-
-cat << EOF > ~/.bash_profile
-#--------------------------------------
-# Standard NCBR .bash_profile
-#--------------------------------------
-
-# include .bashrc if it exists
-if [ -f ~/.bashrc ]; then
-    . ~/.bashrc
-fi
-EOF
-    echo "   ~/.bash_profile"
-
-cat << EOF > ~/.bashrc
-#--------------------------------------
-# Standard NCBR .bashrc
-#--------------------------------------
-
-# use system wide setup
-if [ -f /etc/bashrc ]; then
-    . /etc/bashrc
-fi
-EOF
-    echo "   ~/.bashrc"
-}
-
-# ------------------------------------------------------------------------------
-
-function initenv_print_bottom()
-{
-    echo ""
-    echo "#---------------------------------------------------------"
-    echo "#                  *** End of update ***                  "
-    echo "#                                                         "
-    echo "# = NEW SESSION MUST BE OPENED (LOGOUT AND LOGIN AGAIN) = "
-    echo "#---------------------------------------------------------"
-    echo ""
-}
-
-# ------------------------------------------------------------------------------
 # ------------------------------------------------------------------------------
 
 SHIFT="-"
@@ -162,11 +91,35 @@ shift
 
 case "$ACTION" in
 # -----------------------------
+    "useradd" )
+        AUSER="$2"
+        if [ -z "$AUSER" ]; then
+            AUSER="`whoami`"
+        fi
+        sudo $AMS_PERSONAL_ROOT/share/personal/ams-personal-useradd "$AUSER" || exit 1
+        exit 0
+        ;;
+esac
+
+# -----------------------------------------------------------------------------------------
+
+id -G -n 2> /dev/null | grep "infinity" &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "" 1>&2
+    echo ">>> ERROR: This action requires that you are a member of the infinity group!" 1>&2
+    echo "" 1>&2
+    echo "           Run the following command to fix the problem:" 1>&2
+    echo "           $ ams-personal useradd" 1>&2
+    echo "" 1>&2
+    exit 1
+fi
+
+# this action does not require full Infinity activation
+
+case "$ACTION" in
+# -----------------------------
     "envinit" )
-        initenv_print_header
-        initenv_backup_old_files || exit 1
-        initenv_create_new_files || exit 1
-        initenv_print_bottom
+        $AMS_PERSONAL_ROOT/share/personal/ams-personal-envinit || exit 1
         exit 0
         ;;
 esac
@@ -179,7 +132,7 @@ if [ -z "$AMS_ROOT" ]; then
     echo "" 1>&2
     echo ">>> ERROR: AMS_ROOT is not set!" 1>&2
     echo "           You need to modify your startup files by running the command:" 1>&2
-    echo ""
+    echo "" 1>&2
     echo "           $ ams-personal initenv" 1>&2
     echo "" 1>&2
     exit 1
@@ -188,7 +141,7 @@ fi
 id -G -n 2> /dev/null | grep "sudo" &> /dev/null
 if [ $? -ne 0 ]; then
     echo "" 1>&2
-    echo ">>> ERROR: The user running this script must be in the \"sudo\" group!" 1>&2
+    echo ">>> ERROR: This action can be performed by the administrator only (the \"sudo\" user)!" 1>&2
     echo "" 1>&2
     exit 1
 fi
@@ -196,7 +149,7 @@ fi
 case "$ACTION" in
 # -----------------------------
     "addmodules" )
-        sudo -u infinity -i $AMS_ROOT/share/scripts/ams-sync personal bldlib
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib
         echo ""
         echo "# AMS modules for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
         echo "# ------------------------------------------------------------------------------"
@@ -209,15 +162,15 @@ case "$ACTION" in
         CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
         echo $CORE_BUILDS | tr " " "\n"
 
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
         ;;
 # -----------------------------
     "addbuilds" )
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-addbuilds "$@"
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds "$@"
         ;;
 # -----------------------------
     "addcorebuilds" )
-        sudo -u infinity -i $AMS_ROOT/share/scripts/ams-sync personal bldlib
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib
         echo ""
         echo "# AMS core builds for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
         echo "# ------------------------------------------------------------------------------"
@@ -230,15 +183,15 @@ case "$ACTION" in
         CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
         echo $CORE_BUILDS | tr " " "\n"
 
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
         ;;
 # -----------------------------
     "update" )
-        sudo -u infinity -i $AMS_ROOT/share/scripts/ams-sync personal softrepo
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal softrepo
         ;;
 # -----------------------------
     "upgrade" )
-        sudo -u infinity -i $AMS_ROOT/share/scripts/ams-sync personal bldlib
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib
         echo ""
         echo "# AMS best builds for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
         echo "# ------------------------------------------------------------------------------"
@@ -251,11 +204,11 @@ case "$ACTION" in
         CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
         echo $CORE_BUILDS | tr " " "\n"
 
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS
         ;;
 # -----------------------------
     "rmbuilds" )
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-rmbuilds "$@"
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-rmbuilds "$@"
         ;;
 # -----------------------------
     "debdeps" )
@@ -270,19 +223,11 @@ case "$ACTION" in
         ;;
 # -----------------------------
     "gensshkeys" )
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-gensshkeys "$@"
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-gensshkeys "$@"
         ;;
 # -----------------------------
     "showsshkey" )
-        sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-showsshkey "$@"
-        ;;
-# -----------------------------
-    "useradd" )
-        AUSER="$2"
-        if [ -z "$AUSER" ]; then
-            AUSER="`whoami`"
-        fi
-        sudo $AMS_ROOT/share/personal/ams-personal-useradd "$AUSER"
+        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-showsshkey "$@"
         ;;
 # -----------------------------
     *)
