ams-personal

diff --git a/share/personal/ams-personal-useradd b/share/personal/ams-personal-useradd
--- a/share/personal/ams-personal-useradd
+++ b/share/personal/ams-personal-useradd
@@ -34,6 +34,15 @@ function print_header()
         echo "" 2>&1
         exit 1
     fi
+
+    getent group infinity  &> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "" 2>&1
+        echo ">>> ERROR: The infinity group does not exist!" 2>&1
+        echo "           This is a configuration problem!" 2>&1
+        echo "" 2>&1
+        exit 1
+    fi
 }
 
 # --------------------------------------
