update

diff --git a/share/personal/ams-personal-install b/share/personal/ams-personal-install
--- a/share/personal/ams-personal-install
+++ b/share/personal/ams-personal-install
@@ -3,10 +3,17 @@
 # Advanced Module System synchronization utility for personal site
 # ------------------------------------------------------------------------------
 
+umask 022
+
+AMS_SRC_HOST=personal@softrepo.ncbr.muni.cz
+
+# ------------------------------------------------
+
 function print_header()
 {
+    echo
     echo "#-------------------------------------------------------------------------------"
-    echo "#                             *** Installing builds ***                         "
+    echo "#                         *** Installing modules/builds ***                     "
     echo "#-------------------------------------------------------------------------------"
 }
 
@@ -32,160 +39,140 @@ function print_usage()
 
 # --------------------------------------
 
-function sync_ams_builds(){
-
+function get_origins() {
     echo "" | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "# 1) Syncing library of AMS builds  ..." | tee -a $LOG_FILE
+    echo "# 1) Getting module origins ..." | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "" | tee -a $LOG_FILE
 
-    ams-sync personal bldlib >> $LOG_FILE 2>&1
+    rm -rf "$MODULE_ORIGINS"
 
-    if [ $? -eq 0 ]; then
-        echo "AMS build library synchronization ... [OK]"
-    else
-        echo "AMS build library synchronization ... [FAILED]"
-        show_log_error
-        exit 1
-    fi
-}
-
-# --------------------------------------
-
-function sync_deps() {
-
-    local PREFIX
-    local BUILD
-    local SYNC_BUILD
-    local FULL_SYNC_BUILD
-
-    INSTALL_BUILDS="$INSTALL_BUILDS $1"
-    ((NBUILDS++))
-
-    PREFIX="`dirname $1`"
-    BUILD="`basename $1`"
-    if [ "$PREFIX" == "." ]; then PREFIX=""; fi
-    for SYNC_BUILD in `ams-map-manip --prefix "$PREFIX" showsyncdeps personal "$BUILD"`; do  
-        # complete incomplete build names
-        # do not use prefix in the next call - SYNC_BUILD is without prefix, which need to be autodetermined
-        FULL_SYNC_BUILD=`ams-map-manip bestbuild personal "$SYNC_BUILD"`
-        if [ -n "$FULL_SYNC_BUILD" ]; then
-            printf "      |-> %-40s => %-40s\n" "$SYNC_BUILD" "$FULL_SYNC_BUILD" | tee -a $LOG_FILE
-            sync_deps "$FULL_SYNC_BUILD"
-            ((NBUILDS++))
-        else
-            printf "      |-> %-40s => NOT FOUND\n" "$SYNC_BUILD" | tee -a $LOG_FILE
-        fi
+    for MODULE in "$@"; do
+        echo ">> $MODULE" | tee -a $LOG_FILE
+        ssh -x $AMS_SRC_HOST amsmodule allorigins "$MODULE" 2>&1 | tee -a "$MODULE_ORIGINS" | tee -a $LOG_FILE
     done
 }
 
 # --------------------------------------
 
-function check_builds() {
+function download_origins() {
 
     echo "" | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "# 2) Checking requested builds and their dependencies ..." | tee -a $LOG_FILE
+    echo "# 2) Downloading origins ..." | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
     echo "" | tee -a $LOG_FILE
-    echo "# Number of requests : $#" | tee -a $LOG_FILE
+    echo "# Number of files : `cat $MODULE_ORIGINS | wc -l`" | tee -a $LOG_FILE
     echo ""
 
-    INSTALL_BUILDS=""
-    while [ $# -ne 0 ]; do
-        ABUILD="$1"
-        printf ">>> %-60s\n" "$ABUILD"  | tee -a $LOG_FILE
-        APREFIX="`dirname $ABUILD`"
-        ABUILD="`basename $ABUILD`"
-        if [ "$APREFIX" == "." ]; then APREFIX=""; fi
-        BUILDS=`ams-map-manip --prefix "$APREFIX" showautobuilds personal "$ABUILD" 2> /dev/null`
-        NBUILDS=0
-        for BUILD in $BUILDS; do
-            printf "    %s\n" $BUILD  | tee -a $LOG_FILE
-            sync_deps "$BUILD"
-        done
-        printf "    Number of builds: %d\n" $NBUILDS  | tee -a $LOG_FILE
-        shift
-    done
-    INSTALL_BUILDS="`echo $INSTALL_BUILDS | tr " " "\n" | sort -u`"
+    mkdir -p $SOFTREPO/_ams_bundle/blds
+    if [ $? -ne 0 ]; then
+        echo "" 1>&2
+        echo ">>> ERROR: Unable to create '$SOFTREPO/_ams_bundle/blds'!" 1>&2
+        exit 1
+    fi
+
+    while read FILE; do
+        scp $AMS_SRC_HOST:$FILE "$SOFTREPO/_ams_bundle/blds/"
+    done < <( cat "$MODULE_ORIGINS" )
 }
 
 # --------------------------------------
 
-function add_builds_to_map(){
+function local_index(){
 
     echo "" | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "# 3) Adding builds to the map ..." | tee -a $LOG_FILE
+    echo "# 3) Updating local index ..." | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
     echo "" | tee -a $LOG_FILE
-    echo "Number of builds: `echo $INSTALL_BUILDS | wc --words`" | tee -a $LOG_FILE
-    echo "" | tee -a $LOG_FILE
 
-    for BUILD in $INSTALL_BUILDS; do
-        printf "Adding %-60s ..." $BUILD | tee -a $LOG_FILE
-        PREFIX="`dirname $BUILD`"
-        BUILD="`basename $BUILD`"
-        if [ "$PREFIX" == "." ]; then PREFIX=""; fi
-        ams-map-manip --prefix "$PREFIX" addbuilds all "$BUILD" >> $LOG_FILE 2>&1
+    cd $SOFTREPO
+    ams-bundle rebuild
+    ams-bundle index new
+}
+
+# --------------------------------------
+
+function remote_index(){
+
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 4) Getting remote index ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+
+    cd $SOFTREPO
+    ams-bundle sources - | \
+               ssh -x $AMS_SRC_HOST ams-index-create --personal builds - $SOFTREPO - \
+                    > $SOFTREPO/_ams_bundle/index.old
+}
+
+# --------------------------------------
+
+function sync_softrepo(){
+
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 5) Syncing builds ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+
+    echo "# Changed builds ..." | tee -a $LOG_FILE
+    ams-bundle --silent index diff | tee -a $LOG_FILE
+    if [ $? -ne 0 ]; then exit 1; fi;
+
+    NCHANGES="`ams-bundle --silent index diff | wc -l`"
+    if [ "$NCHANGES" -eq 0 ]; then
+        echo "> No changed builds were detected ..."
+        rm -f "$NEW_INDEX"
+        return
+    fi
+
+    ams-bundle --silent --skipremoved index diff | while read STATUS SHA1 BUILD AMS_PACKAGE_DIR; do
+
+        if [[ ("$STATUS" != "+") && ("$STATUS" != "M") ]]; then continue; fi
+        if [[ -z "$AMS_PACKAGE_DIR" ]]; then contine; fi
+        if [[ -z "$BUILD" ]]; then contine; fi
+
+        (
+        printf "%-60s " "$BUILD"
+        echo "==== $BUILD" >> $LOG_FILE
+
+        # create app root directory
+        mkdir -p "$SOFTREPO/$AMS_PACKAGE_DIR/"
         if [ $? -ne 0 ]; then
-            echo " [FAILED]"
+            echo "             [FAILED]"
+            echo "   Unable to create directory: '$SOFTREPO/$AMS_PACKAGE_DIR/'"
+            show_log_error
+            exit 1
+        fi
+
+        # copy data
+        rsync -e "ssh -x" -av --delete $AMS_RSYNC_OPTS \
+                "$AMS_SRC_HOST:$SOFTREPO/$AMS_PACKAGE_DIR/" "$SOFTREPO/$AMS_PACKAGE_DIR/" >> $LOG_FILE 2>&1
+        if [ $? -ne 0 ]; then
+            echo "             [FAILED]"
             show_log_error
             exit 1
         else
-            echo " [OK]"
+            echo "             [SYNC]"
         fi
+        ) < /dev/null
+        if [ $? -ne 0 ]; then exit 1; fi
     done
-}
+    if [ $? -ne 0 ]; then exit 1; fi
 
-# --------------------------------------
-
-function rebuild_map_and_cache(){
-
-    echo "" | tee -a $LOG_FILE
-    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "# 4) Rebuilding map and cache ..." | tee -a $LOG_FILE
-    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-
-    umask 022
-
-    ams-map-manip distribute  >> $LOG_FILE 2>&1
-    if [ $? -eq 0 ]; then
-        echo "AMS map distributed               ... [OK]"
-    else
-        echo "AMS map distributed               ... [FAILED]"
-        show_log_error
-        exit 1
-    fi
-
-    ams-cache rebuildall  >> $LOG_FILE 2>&1
-    if [ $? -eq 0 ]; then
-        echo "AMS module cache rebuilded        ... [OK]"
-    else
-        echo "AMS module cache rebuilded        ... [FAILED]"
-        show_log_error
-        exit 1
-    fi
-}
-
-# --------------------------------------
-
-function sync_site(){
-
-    echo "" | tee -a $LOG_FILE
-    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "# 5) Syncing site ..." | tee -a $LOG_FILE
-    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-
-    ams-sync personal softrepo | tee -a $LOG_FILE
+# commit changes
+    ams-bundle index commit >> $LOG_FILE 2>&1
 }
 
 # --------------------------------------
 
 function print_bottom()
 {
+    echo
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
-    echo "#                        *** End of build installation ***                      " | tee -a $LOG_FILE
+    echo "#                      *** End of modules/builds installation ***               " | tee -a $LOG_FILE
     echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
 }
 
@@ -207,37 +194,36 @@ if [ $# -le 0 ]; then
     exit 1
 fi
 
-# check if AMS_ROOT is set -----------------------
-if [ -z "$AMS_ROOT" ]; then
+# check if $AMS_ROOT_V9 is set -----------------------
+if [ -z "$AMS_ROOT_V9" ]; then
     echo "" 1>&2
-    echo ">>> ERROR: AMS_ROOT variable is not set!" 1>&2
+    echo ">>> ERROR: $AMS_ROOT_V9 variable is not set!" 1>&2
     echo "" 1>&2
     exit 1
 fi
 
 # ------------------------------------------------
 
-umask 027
-mkdir -p "$AMS_ROOT/var/personal/logs"
+mkdir -p "$AMS_ROOT_V9/var/personal/logs"
 if [ $? -ne 0 ]; then
     echo "" 1>&2
-    echo ">>> ERROR: Unable to create $AMS_ROOT/var/personal/logs directory!" 1>&2
+    echo ">>> ERROR: Unable to create $AMS_ROOT_V9/var/personal/logs directory!" 1>&2
     echo "" 1>&2
     exit 1
 fi
 
 # log file
-LOG_FILE="$AMS_ROOT/var/personal/logs/`date +%Y-%m-%d#%H:%M:%S`.log"
+LOG_FILE="$AMS_ROOT_V9/var/personal/logs/`date +%Y-%m-%d#%H:%M:%S`.log"
 
 echo ">>> Log file: $LOG_FILE"
 
-INSTALL_BUILDS=""
-sync_ams_builds
-check_builds "$@"
-add_builds_to_map
-rebuild_map_and_cache
-sync_site
+MODULE_ORIGINS="$AMS_ROOT_V9/var/personal/module_origins.$$"
 
+get_origins "$@"
+download_origins
+local_index
+remote_index
+sync_softrepo
 print_bottom
 
 echo ""
