ams-personal

diff --git a/share/personal/ams-personal-addbuilds b/share/personal/ams-personal-addbuilds
--- a/share/personal/ams-personal-addbuilds
+++ b/share/personal/ams-personal-addbuilds
@@ -5,10 +5,20 @@
 
 function print_header()
 {
-    echo ""
-    echo "#-------------------------------------------------------------------------------"
-    echo "#                             *** Installing builds ***                         "
-    echo "#-------------------------------------------------------------------------------"
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "#                             *** Installing builds ***                         " | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+}
+
+# ------------------------------------------------
+
+show_log_error()
+{
+    echo "" 1>&2
+    echo ">>> ERROR: Log file: $LOG_FILE" 1>&2
+    tail -10 "$LOG_FILE" 1>&2
+    echo "" 1>&2
 }
 
 # ------------------------------------------------
@@ -24,41 +34,47 @@ function print_usage()
 
 function sync_ams_builds(){
 
-    echo ""
-    echo "#-------------------------------------------------------------------------------"
-    echo "# 1) Syncing library of AMS builds  ..."
-    echo "#-------------------------------------------------------------------------------"
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 1) Syncing library of AMS builds  ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
 
-    ams-sync personal amsbuilds
+    ams-sync personal amsbuilds >> $LOG_FILE 2>&1
+
+    if [ $? -eq 0 ]; then
+        echo "AMS builds synchronization [OK]"
+    else
+        echo "AMS builds synchronization [FAILED]"
+        show_log_error
+        exit 1
+    fi
 }
 
 # --------------------------------------
 
 function check_builds(){
 
-    echo ""
-    echo "#-------------------------------------------------------------------------------"
-    echo "# 2) Checking requested builds and their dependencies ..."
-    echo "#-------------------------------------------------------------------------------"
-    echo ""
-    echo "Number of builds: $#"
-    echo ""
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 2) Checking requested builds and their dependencies ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "" | tee -a $LOG_FILE
 
     while [ $# -ne 0 ]; do
         ABUILD="$1"
-        printf ">>> %-40s ... \n" "$ABUILD"
+        printf ">>> %-40s ... \n" "$ABUILD"  | tee -a $LOG_FILE
         APREFIX="`dirname $ABUILD`"
         ABUILD="`basename $ABUILD`"
         if [ "$APREFIX" == "." ]; then APREFIX=""; fi
         BUILDS=`ams-map-manip --prefix "$APREFIX" getbuilds personal "$ABUILD" 2> /dev/null`
         NBUILDS=0
         for BUILD in $BUILDS; do
-            printf "    %s\n" $BUILD
+            printf "    %s\n" $BUILD  | tee -a $LOG_FILE
             PREFIX="`dirname $BUILD`"
             BUILD="`basename $BUILD`"
             if [ "$PREFIX" == "." ]; then PREFIX=""; fi
             for SYNC_BUILD in `ams-map-manip --prefix "$PREFIX" deepsyncdeps personal "$BUILD"`; do
-                printf "    |-> %-40s\n" "$SYNC_BUILD"
+                printf "    |-> %-40s\n" "$SYNC_BUILD"  | tee -a $LOG_FILE
                 if [ -n "$PREFIX" ]; then SYNC_BUILD="$PREFIX/$SYNC_BUILD"; fi
                 INSTALL_BUILDS="$INSTALL_BUILDS $SYNC_BUILD"
                 ((NBUILDS++))
@@ -67,7 +83,7 @@ function check_builds(){
             INSTALL_BUILDS="$INSTALL_BUILDS $BUILD"
             ((NBUILDS++))
         done
-        printf "    Number of builds: %d\n" $NBUILDS
+        printf "    Number of builds: %d\n" $NBUILDS  | tee -a $LOG_FILE
         shift
     done
     INSTALL_BUILDS="`echo $INSTALL_BUILDS | tr " " "\n" | sort -u`"
@@ -77,20 +93,27 @@ function check_builds(){
 
 function add_builds_to_map(){
 
-    echo ""
-    echo "#-------------------------------------------------------------------------------"
-    echo "# 3) Adding builds to the map ..."
-    echo "#-------------------------------------------------------------------------------"
-    echo ""
-    echo "Number of builds: `echo $INSTALL_BUILDS | wc --words`"
-    echo ""
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 3) Adding builds to the map ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "" | tee -a $LOG_FILE
+    echo "Number of builds: `echo $INSTALL_BUILDS | wc --words`" | tee -a $LOG_FILE
+    echo "" | tee -a $LOG_FILE
 
     for BUILD in $INSTALL_BUILDS; do
-        echo "Adding $BUILD ..."
+        echo -n "Adding $BUILD ... " | tee -a $LOG_FILE
         PREFIX="`dirname $BUILD`"
         BUILD="`basename $BUILD`"
         if [ "$PREFIX" == "." ]; then PREFIX=""; fi
-        ams-map-manip --prefix "$PREFIX" addbuilds all "$BUILD"
+        ams-map-manip --prefix "$PREFIX" addbuilds all "$BUILD" >> $LOG_FILE 2>&1
+        if [ $? -ne 0 ]; then
+            echo "             [FAILED]"
+            show_log_error
+            exit 1
+        else
+            echo "             [SYNC]"
+        fi
     done
 }
 
@@ -98,33 +121,53 @@ function add_builds_to_map(){
 
 function rebuild_map_and_cache(){
 
-    echo "#-------------------------------------------------------------------------------"
-    echo "# 4) Rebuilding map and cache ..."
-    echo "#-------------------------------------------------------------------------------"
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 4) Rebuilding map and cache ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
 
-    ams-map-manip distribute
-    ams-cache rebuildall
+    umask 022
+
+    ams-map-manip distribute  >> $LOG_FILE 2>&1
+    if [ $? -eq 0 ]; then
+        echo "AMS map distributed [OK]"
+    else
+        echo "AMS map distributed [FAILED]"
+        show_log_error
+        exit 1
+    fi
+
+    ams-cache rebuildall  >> $LOG_FILE 2>&1
+    if [ $? -eq 0 ]; then
+        echo "AMS module cache rebuilded [OK]"
+    else
+        echo "AMS module cache rebuilded [FAILED]"
+        show_log_error
+        exit 1
+    fi
 }
 
 # --------------------------------------
 
 function sync_site(){
 
-    echo "#-------------------------------------------------------------------------------"
-    echo "# 5) Syncing site ..."
-    echo "#-------------------------------------------------------------------------------"
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "# 5) Syncing site ..." | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
 
-    ams-sync personal softrepo
+    ams-sync personal softrepo | tee -a $LOG_FILE
 }
 
 # --------------------------------------
 
 function print_bottom()
 {
-    echo "#-------------------------------------------------------------------------------"
-    echo "#                        *** End of build installation ***                      "
-    echo "#-------------------------------------------------------------------------------"
-    echo ""
+    echo "" | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "#                        *** End of build installation ***                      " | tee -a $LOG_FILE
+    echo "#-------------------------------------------------------------------------------" | tee -a $LOG_FILE
+    echo "" | tee -a $LOG_FILE
 }
 
 # ------------------------------------------------------------------------------
@@ -155,6 +198,19 @@ fi
 
 # ------------------------------------------------
 
+mkdir -p "$AMS_ROOT/var/personal/logs"
+if [ $? -ne 0 ]; then
+    echo "" 1>&2
+    echo ">>> ERROR: Unable to create $AMS_ROOT/var/personal/logs directory!" 1>&2
+    echo "" 1>&2
+    exit 1
+fi
+
+# log file
+LOG_FILE="$AMS_ROOT/var/personal/logs/`date +%Y-%m-%d#%H:%M:%S`.log"
+
+echo ">>> Log file: $LOG_FILE"
+
 INSTALL_BUILDS=""
 sync_ams_builds
 check_builds "$@"
@@ -162,6 +218,10 @@ add_builds_to_map
 rebuild_map_and_cache
 sync_site
 
+echo ""
+echo "END: Log file is in: $LOG_FILE"
+
 print_bottom
+
 
 
diff --git a/share/sync/rsync/ams-rsync-pull b/share/sync/rsync/ams-rsync-pull
--- a/share/sync/rsync/ams-rsync-pull
+++ b/share/sync/rsync/ams-rsync-pull
@@ -109,8 +109,14 @@ rsync_amscore_cache()
 
     umask 022
     SITES="`echo $AMS_SYNC_SITES | tr ' ' '\n' | awk '{ if( NR > 1 ) printf(","); printf("%s",$1) }'`"
-    $AMS_ROOT/bin/ams-cache --sites "$SITES" rebuildall | tee -a $LOG_FILE
-    if [ $? -ne 0 ]; then exit 1; fi;
+    $AMS_ROOT/bin/ams-cache --sites "$SITES" rebuildall >> $LOG_FILE 2>&1
+    if [ $? -eq 0 ]; then
+        echo "AMS module cache updated [OK]"
+    else
+        echo "AMS module cache updated [FAILED]"
+        show_log_error
+        exit 1
+    fi
 
 }
 
