ams-personal

diff --git a/share/personal/ams-personal b/share/personal/ams-personal
--- a/share/personal/ams-personal
+++ b/share/personal/ams-personal
@@ -4,7 +4,7 @@
 # (c) 2017 Petr Kulhanek
 # ------------------------------------------------------------------------------
 
-# ------------------------------------------------
+# ------------------------------------------------------------------------------
 
 function print_usage()
 {
@@ -31,7 +31,7 @@ function print_usage()
     echo ""
     echo "Supported actions for ordinary user:"
     echo "   Personal site setup:"
-    echo "       envinit            initialize bash startup files for the current user"
+    echo "       initenv            initialize bash startup files for the current user"
     echo ""
     echo "General pre-requisites for a computer:"
     echo "       * ncbr-ams-core-X.Y-personal package must by installed"
@@ -44,7 +44,85 @@ function print_usage()
 
 }
 
-# ------------------------------------------------
+# ------------------------------------------------------------------------------
+
+function initenv_print_header()
+{
+    echo ""
+    echo "#------------------------------------------------------"
+    echo "#    *** Shell Environment Startup File Update ***     "
+    echo "#------------------------------------------------------"
+}
+
+# ------------------------------------------------------------------------------
+
+function initenv_backup_old_files()
+{
+    echo ""
+    echo "1) Backuping old user startup files ..."
+
+    SEQ=`date +"%s"`
+    if [ -f ~/.profile ]; then
+        mv ~/.profile ~/.profile.$SEQ
+        echo "   ~/.profile        -> ~/.profile.$SEQ"
+    fi
+    if [ -f ~/.bash_profile ]; then
+        mv ~/.bash_profile ~/.bash_profile.$SEQ
+        echo "   ~/.bash_profile   -> ~/.bash_profile.$SEQ"
+    fi
+    if [ -f ~/.bashrc ]; then
+        mv ~/.bashrc ~/.bashrc.$SEQ
+        echo "   ~/.bashrc         -> ~/.bashrc.$SEQ"
+    fi
+}
+
+# ------------------------------------------------------------------------------
+
+function initenv_create_new_files()
+{
+    echo ""
+    echo "2) Creating new user startup files ..."
+
+cat << EOF > ~/.bash_profile
+#--------------------------------------
+# Standard NCBR .bash_profile
+#--------------------------------------
+
+# include .bashrc if it exists
+if [ -f ~/.bashrc ]; then
+    . ~/.bashrc
+fi
+EOF
+    echo "   ~/.bash_profile"
+
+cat << EOF > ~/.bashrc
+#--------------------------------------
+# Standard NCBR .bashrc
+#--------------------------------------
+
+# use system wide setup
+if [ -f /etc/bashrc ]; then
+    . /etc/bashrc
+fi
+EOF
+    echo "   ~/.bashrc"
+}
+
+# ------------------------------------------------------------------------------
+
+function initenv_print_bottom()
+{
+    echo ""
+    echo "#---------------------------------------------------------"
+    echo "#                  *** End of update ***                  "
+    echo "#                                                         "
+    echo "# = NEW SESSION MUST BE OPENED (LOGOUT AND LOGIN AGAIN) = "
+    echo "#---------------------------------------------------------"
+    echo ""
+}
+
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
 
 SHIFT="-"
 while [ -n "$SHIFT" ]; do
@@ -64,11 +142,46 @@ if [ $# -lt 1 ]; then
     exit 1
 fi
 
+# -----------------------------------------------------------------------------------------
+
+# this action does not require full Infinity activation
+
+case "$ACTION" in
+# -----------------------------
+    "initenv" )
+        initenv_print_header
+        initenv_backup_old_files || exit 1
+        initenv_create_new_files || exit 1
+        initenv_print_bottom
+        exit 0
+        ;;
+esac
+
+# -----------------------------------------------------------------------------------------
+
 # check if AMS_ROOT is set -----------------------
 
 if [ -z "$AMS_ROOT" ]; then
     echo "" 1>&2
     echo ">>> ERROR: AMS_ROOT is not set!" 1>&2
+    echo "           You need to modify your startup files by running the command:" 1>&2
+    echo ""
+    echo "           $ ams-personal initenv" 1>&2
+    echo "" 1>&2
+    exit 1
+fi
+
+if [ "`id -g -n`" == "infinity" ] || [ "`id -u -n`" == "root" ]; then
+    echo "" 1>&2
+    echo ">>> ERROR: The ams-personal command cannot be run by 'infinity' or 'root' users!" 1>&2
+    echo "" 1>&2
+    exit 1
+fi
+
+id -G -n 2> /dev/null | grep "sudo" &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "" 1>&2
+    echo ">>> ERROR: The user running this script must be in the \"sudo\" group!" 1>&2
     echo "" 1>&2
     exit 1
 fi
@@ -139,10 +252,6 @@ case "$ACTION" in
 # -----------------------------
     "rmbuilds" )
         sudo -u infinity -i $AMS_ROOT/share/personal/ams-personal-rmbuilds "$@"
-        ;;
-# -----------------------------
-    "envinit" )
-        $AMS_ROOT/share/personal/ams-personal-envinit "$@"
         ;;
 # -----------------------------
     "gensshkeys" )
