ams-personal

diff --git a/share/personal/ams-personal-install b/share/personal/ams-personal-install
--- a/share/personal/ams-personal-install
+++ b/share/personal/ams-personal-install
@@ -9,6 +9,13 @@ function print_header()
     echo "#-------------------------------------------------------------------------------"
     echo "#                             *** Installing builds ***                         "
     echo "#-------------------------------------------------------------------------------"
+
+    if [ "`id -u -n`" != "infinity" ]; then
+        echo "" 2>&1
+        echo ">>> ERROR: This script must be run by the infinity user!"  2>&1
+        print_usage  2>&1
+        exit 1
+    fi
 }
 
 # ------------------------------------------------
@@ -16,7 +23,7 @@ function print_header()
 function print_usage()
 {
     echo ""
-    echo "Usage: sudo -u infinity ams-personal-install [-h | --help] <[prefix/]build1> [[prefix/]build2 [prefix/]build3 ...]"
+    echo "    Usage: sudo -u infinity -i ams-personal-install [-h | --help] <[prefix/]build1> [[prefix/]build2 [prefix/]build3 ...]"
     echo ""
 }
 
@@ -73,7 +80,7 @@ function add_builds_to_map(){
         PREFIX="`dirname $BUILD`"
         BUILD="`basename $BUILD`"
         if [ "$PREFIX" == "." ]; then PREFIX=""; fi
-        ams-map-manip --prefix "$PREFIX" addbuilds personal "$BUILD"
+        ams-map-manip --prefix "$PREFIX" addbuilds all "$BUILD"
     done
 }
 
@@ -128,7 +135,7 @@ done
 if [ $# -le 0 ]; then
     echo "" 1>&2
     echo ">>> ERROR: Incorrect number of arguments!" 1>&2
-    print_usage
+    print_usage 2>&1
     exit 1
 fi
 
diff --git a/share/personal/ams-personal-useradd b/share/personal/ams-personal-useradd
--- a/share/personal/ams-personal-useradd
+++ b/share/personal/ams-personal-useradd
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+AMS_PERS=/software/ncbr/softmods/8.0/share/personal
+
 function print_header()
 {
     echo ""
@@ -7,12 +9,31 @@ function print_header()
     echo "# *** Add the current user into the infinity group *** "
     echo "#------------------------------------------------------"
 
-    if [ "`id -u`" != "root" ]; then
-        echo ""
-        echo ">>> ERROR: This script must be run by the root user!"
-        echo ""
-        echo "    \$ sudo ams-personal-useradd"
-        echo ""
+    if [ "`id -u -n`" != "root" ]; then
+        echo "" 2>&1
+        echo ">>> ERROR: This script must be run by the root user!" 2>&1
+        echo "" 2>&1
+        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
+        echo "" 2>&1
+        exit 1
+    fi
+
+    if [ -z "$1" ]; then
+        echo "" 2>&1
+        echo ">>> ERROR: User not specified!" 2>&1
+        echo "" 2>&1
+        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
+        echo "" 2>&1
+        exit 1
+    fi
+
+    id -- "$1" &> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "" 2>&1
+        echo ">>> ERROR: User '$1' does not exist!" 2>&1
+        echo "" 2>&1
+        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
+        echo "" 2>&1
         exit 1
     fi
 }
@@ -22,7 +43,14 @@ function print_header()
 function add_user_to_infinity()
 {
     echo ""
-    # TODO
+    echo "# Adding user '$1' into the infinity group ..."
+    usermod -a -G infinity -- "$1"
+    if [ $? -ne 0 ] ; then
+        echo "" 2>&1
+        echo ">>> ERROR: Unable to add user '$1' to the infinity group!" 2>&1
+        echo "" 2>&1
+        exit 1
+    fi
 }
 
 # --------------------------------------
@@ -40,8 +68,8 @@ function print_bottom()
 
 # --------------------------------------
 
-print_header
-add_user_to_infinity
+print_header "$@"
+add_user_to_infinity "$@"
 print_bottom
 
 
